// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: trade.proto

#include "trade.pb.h"
#include "trade.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace trade {

static const char* MatchingEngine_method_names[] = {
  "/trade.MatchingEngine/PlaceOrder",
};

std::unique_ptr< MatchingEngine::Stub> MatchingEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MatchingEngine::Stub> stub(new MatchingEngine::Stub(channel, options));
  return stub;
}

MatchingEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PlaceOrder_(MatchingEngine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MatchingEngine::Stub::PlaceOrder(::grpc::ClientContext* context, const ::trade::OrderRequest& request, ::trade::OrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::trade::OrderRequest, ::trade::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PlaceOrder_, context, request, response);
}

void MatchingEngine::Stub::async::PlaceOrder(::grpc::ClientContext* context, const ::trade::OrderRequest* request, ::trade::OrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::trade::OrderRequest, ::trade::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlaceOrder_, context, request, response, std::move(f));
}

void MatchingEngine::Stub::async::PlaceOrder(::grpc::ClientContext* context, const ::trade::OrderRequest* request, ::trade::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlaceOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::trade::OrderResponse>* MatchingEngine::Stub::PrepareAsyncPlaceOrderRaw(::grpc::ClientContext* context, const ::trade::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::trade::OrderResponse, ::trade::OrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PlaceOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::trade::OrderResponse>* MatchingEngine::Stub::AsyncPlaceOrderRaw(::grpc::ClientContext* context, const ::trade::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPlaceOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

MatchingEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchingEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchingEngine::Service, ::trade::OrderRequest, ::trade::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchingEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::trade::OrderRequest* req,
             ::trade::OrderResponse* resp) {
               return service->PlaceOrder(ctx, req, resp);
             }, this)));
}

MatchingEngine::Service::~Service() {
}

::grpc::Status MatchingEngine::Service::PlaceOrder(::grpc::ServerContext* context, const ::trade::OrderRequest* request, ::trade::OrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Backend_method_names[] = {
  "/trade.Backend/ExecuteTrade",
};

std::unique_ptr< Backend::Stub> Backend::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Backend::Stub> stub(new Backend::Stub(channel, options));
  return stub;
}

Backend::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteTrade_(Backend_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Backend::Stub::ExecuteTrade(::grpc::ClientContext* context, const ::trade::TradeRequest& request, ::trade::TradeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::trade::TradeRequest, ::trade::TradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteTrade_, context, request, response);
}

void Backend::Stub::async::ExecuteTrade(::grpc::ClientContext* context, const ::trade::TradeRequest* request, ::trade::TradeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::trade::TradeRequest, ::trade::TradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTrade_, context, request, response, std::move(f));
}

void Backend::Stub::async::ExecuteTrade(::grpc::ClientContext* context, const ::trade::TradeRequest* request, ::trade::TradeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTrade_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::trade::TradeResponse>* Backend::Stub::PrepareAsyncExecuteTradeRaw(::grpc::ClientContext* context, const ::trade::TradeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::trade::TradeResponse, ::trade::TradeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteTrade_, context, request);
}

::grpc::ClientAsyncResponseReader< ::trade::TradeResponse>* Backend::Stub::AsyncExecuteTradeRaw(::grpc::ClientContext* context, const ::trade::TradeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteTradeRaw(context, request, cq);
  result->StartCall();
  return result;
}

Backend::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Backend_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Backend::Service, ::trade::TradeRequest, ::trade::TradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Backend::Service* service,
             ::grpc::ServerContext* ctx,
             const ::trade::TradeRequest* req,
             ::trade::TradeResponse* resp) {
               return service->ExecuteTrade(ctx, req, resp);
             }, this)));
}

Backend::Service::~Service() {
}

::grpc::Status Backend::Service::ExecuteTrade(::grpc::ServerContext* context, const ::trade::TradeRequest* request, ::trade::TradeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace trade

